export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FALSE = 'FETCH_TASK_FALSE';

export const FILTER_TAST = 'FILTER_TAST';
export const FILTER_TAST_SUCCESS = 'FILTER_TAST_SUCCESS';
