export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FALSE = 'FETCH_TASK_FALSE';

export const FILTER_TAST = 'FILTER_TAST';
export const FILTER_TAST_SUCCESS = 'FILTER_TAST_SUCCESS';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FALSE = 'ADD_TASK_FALSE';

export const TASK_EDITING = 'TASK_EDITING';

export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FALSE = 'EDIT_TASK_FALSE';

export const DEL_TASK = 'DEL_TASK';
export const DEL_TASK_SUCCESS = 'DEL_TASK_SUCCESS';
export const DEL_TASK_FALSE = 'DEL_TASK_FALSE';